project:
  type: website
  output-dir: docs
  resources: 
  - materials/*.zip

website:
  title: "Open Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Slides
        menu: 
          - href: "slides/01-overview.qmd"
            text: "01 - Overview"
          - href: "slides/02-rescomp.qmd"
            text: "02 - Research Compendia"
          - href: "slides/03-versioning.qmd"
            text: "03 - Version control"
      - text: Practice
        menu: 
          - href: "practice/02-rescomp.qmd"
            text: "02 - Research Compendia"
          - href: "practice/03-versioning.qmd"
            text: "03 - Version control"


format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true

callout-icon: false
