---
title: "Information"
---

## Instructors

[Dr Stefano Coretta](https://stefanocoretta.github.io) will be your primary instructor and point of contact for the workshop.

[Ponrawee Praesertsom](https://ponraw.ee) will help with running the workshop and facilitating the hands on sessions.

## Location

The workshop will take place in the Dugald Stewart Building (DSB) of the University of Edinburgh in Edinburgh (see map below).

All sessions will be delivered in [Room 3.10](https://www.accessable.co.uk/the-university-of-edinburgh/central-area/access-guides/3-10-peter-ladefoged-room) on the third floor.
Registration and catering will be in the common room of the seventh floor.

If you are unsure of where to go, ask for directions at the building reception.

```{=html}
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2234.2269844597745!2d-3.1905044228483206!3d55.945437677136994!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4887c78481291d57%3A0x308db74e83fd68a5!2sDugald%20Stewart%20Building%2C%20The%20University%20of%20Edinburgh!5e0!3m2!1sen!2suk!4v1777368006049!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
```

There are gender-neutral and accessible toilets on every floor of the building.
The Meadows park next door is an excellent place to relax and recharge between sessions.

## Schedule

| Time        | Location (DSB) |                                             |
|-------------|----------------|---------------------------------------------|
| 9.30-10.00  | 7th floor      | Breakfast and registration                  |
| 10.00-11.00 | 3.10           | Overview                                    |
| 11.00-11.15 |                | *BREAK*                                     |
| 11.15-12.30 | 3.10           | Research Compendia (with hands on practice) |
| 12.30-13.30 | 7th floor      | *LUNCH*                                     |
| 13.30-14.30 | 3.10           | Version Control (with hands on practice)    |
| 14.30-14.45 |                | *BREAK*                                     |
| 14.45-15.30 | 3.10           | Preregistration and Registered Reports      |
| 15.30-16.00 | 7th floor      | *BREAK*                                     |
| 16.00-17.00 | 3.10           | (optional) Clinic                           |

The clinic (16.00-17.00) is optional: you will get the chance to ask Stefano about how to implement any of the practices covered during the workshop in your own research.
This will be on a first ask first served basis.

## Pre-requisites

Before the workshop, you must read and practice the following tutorial:

> Learning the basics of using the Command Line: <https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Environment_setup/Command_line>

You will need the skills covered in that tutorial to complete the session on version control.

I also recommend you skim this very short paper:

> Crüwell, Sophia, Johnny van Doorn, Alexander Etz, Matthew C. Makel, Hannah Moshontz, Jesse Niebaum, Amy Orben, Sam Parsons, and Michael Schulte-Mecklenbeck.
> 2019.
> “Seven Easy Steps to Open Science: An Annotated Reading List.” Zeitschrift Für Psychologie 227 (4): 237248. 
> <https://doi.org/10.1027/2151-2604/a000387>
